name: Code Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    name: Code Quality and Validation
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm init -y
          npm install --save-dev htmlhint stylelint eslint
      
      - name: Validate HTML files
        run: |
          echo "🔍 Validating HTML files..."
          for file in *.html pages/*.html admin/*.html; do
            if [ -f "$file" ]; then
              echo "Checking $file"
              # Check for basic HTML structure (skip templates/ as they are fragments)
              if ! grep -q "<!DOCTYPE html>" "$file"; then
                echo "⚠️  Warning: $file missing DOCTYPE declaration"
              fi
              if ! grep -q "<meta charset=" "$file"; then
                echo "⚠️  Warning: $file missing charset meta tag"
              fi
              if ! grep -q "<meta name=\"viewport\"" "$file"; then
                echo "⚠️  Warning: $file missing viewport meta tag"
              fi
            fi
          done
          
          # Validate HTML templates (fragments) separately
          echo "🧩 Validating HTML template fragments..."
          for file in templates/*.html; do
            if [ -f "$file" ]; then
              echo "Checking template fragment: $file"
              # Templates are fragments, so just check for basic HTML validity
              if grep -q "<script>" "$file" && ! grep -q "</script>" "$file"; then
                echo "❌ Error: $file has unclosed script tag"
              fi
              if grep -q "<style>" "$file" && ! grep -q "</style>" "$file"; then
                echo "❌ Error: $file has unclosed style tag"
              fi
            fi
          done
          echo "✅ HTML validation complete"
      
      - name: Validate CSS files
        run: |
          echo "🎨 Validating CSS files..."
          for file in assets/css/*.css assets/css/**/*.css; do
            if [ -f "$file" ]; then
              echo "Checking $file"
              # Basic CSS syntax check
              if ! grep -q "{" "$file"; then
                echo "⚠️  Warning: $file may not contain valid CSS"
              fi
            fi
          done
          echo "✅ CSS validation complete"
      
      - name: Validate JavaScript files
        run: |
          echo "⚡ Validating JavaScript files..."
          for file in assets/js/*.js assets/js/**/*.js; do
            if [ -f "$file" ]; then
              echo "Checking $file"
              # Check for basic JavaScript syntax
              node -c "$file" || echo "⚠️  Syntax error in $file"
            fi
          done
          echo "✅ JavaScript validation complete"
      
      - name: Validate JSON files
        run: |
          echo "📋 Validating JSON files..."
          for file in config/*.json data/*.json; do
            if [ -f "$file" ]; then
              echo "Validating $file"
              python -m json.tool "$file" > /dev/null || echo "❌ Invalid JSON in $file"
            fi
          done
          echo "✅ JSON validation complete"
      
      - name: Check for security issues
        run: |
          echo "🔒 Checking for potential security issues..."
          
          # Check for hardcoded API keys or secrets
          if grep -r -i "api[_-]key\|secret\|password\|token" --include="*.js" --include="*.html" --include="*.css" .; then
            echo "⚠️  Warning: Potential hardcoded secrets found"
          fi
          
          # Check for console.log statements in production files (exclude debug files)
          echo "🔍 Checking for console.log in production files..."
          PRODUCTION_FILES="assets/js/script.js assets/js/main.js assets/js/pages/ assets/js/router.js assets/js/square-functionality.js assets/js/components/"
          CONSOLE_FOUND=false
          
          for pattern in $PRODUCTION_FILES; do
            if [ -d "$pattern" ]; then
              if grep -r "console\.log" "$pattern" --include="*.js" 2>/dev/null; then
                CONSOLE_FOUND=true
              fi
            elif [ -f "$pattern" ]; then
              if grep "console\.log" "$pattern" 2>/dev/null; then
                CONSOLE_FOUND=true
              fi
            fi
          done
          
          if [ "$CONSOLE_FOUND" = true ]; then
            echo "⚠️  Warning: console.log statements found in production code"
          else
            echo "✅ No console.log statements in production files"
          fi
          
          echo "✅ Security check complete"
      
      - name: Performance checks
        run: |
          echo "🚀 Running performance checks..."
          
          # Check file sizes
          echo "📊 File size analysis:"
          find assets/ -type f \( -name "*.js" -o -name "*.css" \) -exec ls -lh {} \; | awk '{print $5, $9}' | sort -hr
          
          # Check for large images
          echo "🖼️  Image size analysis:"
          find assets/images/ -type f 2>/dev/null -exec ls -lh {} \; | awk '{print $5, $9}' | sort -hr | head -10 || echo "No images directory found"
          
          echo "✅ Performance check complete"
      
      - name: Accessibility checks
        run: |
          echo "♿ Checking accessibility features..."
          
          # Check for alt attributes on images
          for file in *.html pages/*.html admin/*.html; do
            if [ -f "$file" ]; then
              if grep -q "<img" "$file" && ! grep -q "alt=" "$file"; then
                echo "⚠️  Warning: $file contains images without alt attributes"
              fi
            fi
          done
          
          # Check for proper heading structure
          for file in *.html pages/*.html admin/*.html; do
            if [ -f "$file" ]; then
              if ! grep -q "<h1" "$file"; then
                echo "⚠️  Warning: $file missing h1 heading"
              fi
            fi
          done
          
          echo "✅ Accessibility check complete"
      
      - name: Generate quality report
        run: |
          echo "📊 Code Quality Report Summary"
          echo "================================"
          echo "✅ HTML files validated"
          echo "✅ CSS files validated"
          echo "✅ JavaScript files validated"
          echo "✅ JSON files validated"
          echo "✅ Security checks completed"
          echo "✅ Performance analysis completed"
          echo "✅ Accessibility checks completed"
          echo ""
          echo "🎉 All quality checks passed!"
